language: python
sudo: false

matrix:
    include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.6
      env: TOXENV=py3-cover,coverage

before_install:
    - cd aws/lambda
    - python -m pip install --upgrade setuptools pip virtualenv

# command to install dependencies
install:
    - pip install -r requirements-build.txt

# command to run tests
script:
    - tox

